version: 0.2

phases:
pre_build:
commands:
- echo Logging in to Amazon ECR...
- aws --version
build:
commands:
- echo Build started
- docker build -t $ML-Project -f Dockerfile .
post_build:
commands:
- echo Build completed

artifacts:
files:
- '**/*'
